language: go

go:
  - "1.8"

install: true
notifications:
  email: false

jobs:
  include:
    - stage: Test
      script:
      - go get -v -d
      - go get github.com/stretchr/testify/assert
      - go get gopkg.in/h2non/gock.v1
      - go test -v -cover